services:
  - type: web
    name: chat-app-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      MONGO_URI: "mongodb+srv://prasanna:user%40123@chat.utr8ma8.mongodb.net/?appName=chat"
      JWT_SECRET: "prassana123"
      CLIENT_URL: "https://chats-app-nine.vercel.app/"
    autoDeploy: true
